import SQL_Connector.Connector;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jayashankaha Deshan
 */
public class ADD_REMOVE_MEMBERS extends javax.swing.JFrame {

    /**
     * Creates new form add_remove_members
     */
    public ADD_REMOVE_MEMBERS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nnumber = new javax.swing.JLabel();
        member_ID = new javax.swing.JLabel();
        SLTC = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        eaddress = new javax.swing.JLabel();
        pnumber = new javax.swing.JLabel();
        ea = new javax.swing.JTextField();
        MID = new javax.swing.JTextField();
        index = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        NIC = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        r = new javax.swing.JButton();
        a = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sltc.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 170));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customers.png"))); // NOI18N
        jLabel3.setText("ADD & REMOVE MEMBERS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 390, 130));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("LIBRARY MANAGEMENT SYSTEM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 410, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimalistic-wallpapers-collection-themefoxx (124).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 540, 570));

        nnumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nnumber.setText("NIC NUMBER");
        getContentPane().add(nnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 150, 80));

        member_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        member_ID.setText("MEMBERSHIP ID");
        getContentPane().add(member_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 150, 50));

        SLTC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SLTC.setText("SLTC INDEX");
        getContentPane().add(SLTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 150, 80));

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.setText("NAME");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 150, 50));

        eaddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eaddress.setText("EMAIL ADDRESS");
        getContentPane().add(eaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 170, 80));

        pnumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnumber.setText("PHONE NUMBER");
        getContentPane().add(pnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 150, 80));
        getContentPane().add(ea, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 320, 40));

        MID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDActionPerformed(evt);
            }
        });
        getContentPane().add(MID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 320, 40));
        getContentPane().add(index, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 320, 40));
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 320, 40));
        getContentPane().add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 320, 40));
        getContentPane().add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 320, 40));

        r.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        r.setForeground(new java.awt.Color(0, 0, 102));
        r.setText("REMOVE");
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 140, 30));

        a.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        a.setForeground(new java.awt.Color(0, 0, 102));
        a.setText("ADD");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
        Add_data();
        close_window();
    }//GEN-LAST:event_aActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
        // TODO add your handling code here:
        Remove_data();
        close_window();
    }//GEN-LAST:event_rActionPerformed

    private void MIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIDActionPerformed

    public void close_window()
    {
        WindowEvent new_event;
        
        new_event = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new_event);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_MEMBERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_MEMBERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_MEMBERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_MEMBERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_REMOVE_MEMBERS().setVisible(true);
            }
        });
    }
    
     public void Add_data()
    {
        
        String member_ID = MID.getText();
        
        String SLTC = index.getText();
        
        String name = n.getText();
        
        String nnumber = NIC.getText();
        
        String pnumber = pn.getText();
        
        String eaddress = ea.getText();
        
        java.sql.Connection connection = Connector.connection();
        
        String SQL = "INSERT INTO members VALUES ('"+member_ID+"','"+name+"','"+SLTC+"','"+nnumber+"','"+eaddress+"','"+pnumber+"')";
        
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           System.out.println("Data Insert Successfully !!");
           
           JOptionPane.showMessageDialog(null,"Member Added to the System Successfully !!");

        }
        catch(Exception error)
        {
            System.out.println("ERROR CODE : "+error);
            
            JOptionPane.showMessageDialog(null,"Attempy Unsuccessful");
        }
        
        
       
        
        
        
    }
    
      public void Remove_data()
    {
        
        String member_ID = MID.getText();
        
        String SLTC = index.getText();
        
        String name = n.getText();
        
        String nnumber = NIC.getText();
        
        String pnumber = pn.getText();
        
        String eaddress = ea.getText();
        
        java.sql.Connection connection = Connector.connection();
        
        String SQL = "DELETE FROM members WHERE MEMBERSHIP_ID = '"+member_ID+"' ";
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           System.out.println("Removed Member Successfully !!");
           
           JOptionPane.showMessageDialog(null,"Removed Member from System Successfully !!");

        }
        catch(Exception error)
        {
            System.out.println("ERROR CODE : "+error);
            
            JOptionPane.showMessageDialog(null,"  Attempt Unsuccessful ");
        }
       
        
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MID;
    private javax.swing.JTextField NIC;
    private javax.swing.JLabel SLTC;
    private javax.swing.JButton a;
    private javax.swing.JTextField ea;
    private javax.swing.JLabel eaddress;
    private javax.swing.JTextField index;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel member_ID;
    private javax.swing.JTextField n;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nnumber;
    private javax.swing.JTextField pn;
    private javax.swing.JLabel pnumber;
    private javax.swing.JButton r;
    // End of variables declaration//GEN-END:variables
}
