import SQL_Connector.Connector;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jayashankaha Deshan
 */
public class ADD_REMOVE_BOOKS extends javax.swing.JFrame {

    /**
     * Creates new form ADD_REMOVE_BOOKS
     */
    public ADD_REMOVE_BOOKS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        book_category = new javax.swing.JLabel();
        book_ID = new javax.swing.JLabel();
        bname = new javax.swing.JLabel();
        book_author = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        BID = new javax.swing.JTextField();
        bn = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        rem = new javax.swing.JButton();
        ad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sltc.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 160));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order.png"))); // NOI18N
        jLabel3.setText("ADD & REMOVE BOOKS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 370, 200));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("LIBRARY MANAGEMENT SYSTEM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 430, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimalistic-wallpapers-collection-themefoxx (124).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 550));

        book_category.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        book_category.setText("CATEGORY");
        getContentPane().add(book_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 140, 30));

        book_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        book_ID.setText("BOOK ID");
        getContentPane().add(book_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 160, 30));

        bname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bname.setText("BOOK NAME");
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 200, 30));

        book_author.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        book_author.setText("AUTHOR");
        getContentPane().add(book_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 150, 30));
        getContentPane().add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 260, 30));
        getContentPane().add(BID, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 260, 30));
        getContentPane().add(bn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 260, 30));
        getContentPane().add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 260, 30));

        rem.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        rem.setForeground(new java.awt.Color(0, 0, 102));
        rem.setText("REMOVE");
        rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remActionPerformed(evt);
            }
        });
        getContentPane().add(rem, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 130, 40));

        ad.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        ad.setForeground(new java.awt.Color(0, 0, 102));
        ad.setText("ADD");
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        getContentPane().add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
        Add_book();
        close_window();
    }//GEN-LAST:event_adActionPerformed

    private void remActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remActionPerformed
        // TODO add your handling code here:
        Remove_book();
        close_window();
    }//GEN-LAST:event_remActionPerformed

    public void close_window()
    {
        WindowEvent new_event;
        
        new_event = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new_event);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_REMOVE_BOOKS().setVisible(true);
            }
        });
    }
    
     public void Add_book()
    {
        
        String book_ID = BID.getText();
        
        String bname = bn.getText();
        
        String book_author = author.getText();
        
        String book_category = category.getText();
        
        java.sql.Connection connection = Connector.connection();
        
        String SQL = "INSERT INTO books VALUES ('"+book_ID+"','"+bname+"','"+book_author+"','"+book_category+"') ";
        
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           System.out.println("Data Insert Successfully !!");
           
           JOptionPane.showMessageDialog(null,"Book Added to the System Successfully !!");

        }
        catch(Exception error)
        {
            System.out.println("ERROR CODE : "+error);
            
            JOptionPane.showMessageDialog(null,"Attempt Unsuccessful");
        }
           
    }
     
      public void Remove_book()
    {
        
        String book_ID = BID.getText();
        
        String bname = bn.getText();
        
        String book_author = author.getText();
        
        String book_category = category.getText();
        
        java.sql.Connection connection = Connector.connection();
        
        String SQL = "DELETE FROM books WHERE BOOK_ID = '"+book_ID+"' ";
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           System.out.println("Removed Book Successfully !!");
           
           JOptionPane.showMessageDialog(null,"Removed Book from System Successfully !!");

        }
        catch(Exception error)
        {
            System.out.println("ERROR CODE : "+error);
            
            JOptionPane.showMessageDialog(null,"Attempt Unsuccessful");
        }
       
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BID;
    private javax.swing.JButton ad;
    private javax.swing.JTextField author;
    private javax.swing.JTextField bn;
    private javax.swing.JLabel bname;
    private javax.swing.JLabel book_ID;
    private javax.swing.JLabel book_author;
    private javax.swing.JLabel book_category;
    private javax.swing.JTextField category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton rem;
    // End of variables declaration//GEN-END:variables
}
