import SQL_Connector.Connector;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jayashankaha Deshan
 */
public class PAYMENT_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form add_remove_members
     */
    public PAYMENT_WINDOW() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        p_ID = new javax.swing.JLabel();
        member_ID = new javax.swing.JLabel();
        mem_name = new javax.swing.JLabel();
        book_I = new javax.swing.JLabel();
        tax = new javax.swing.JLabel();
        MID = new javax.swing.JTextField();
        member_name = new javax.swing.JTextField();
        book_ID = new javax.swing.JTextField();
        pay_ID = new javax.swing.JTextField();
        fine = new javax.swing.JTextField();
        done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sltc.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 170));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment-card.png"))); // NOI18N
        jLabel3.setText("PAYMENT WINDOW");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 390, 130));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("LIBRARY MANAGEMENT SYSTEM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 410, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimalistic-wallpapers-collection-themefoxx (124).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 540, 570));

        p_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p_ID.setText("PAYMENT ID");
        getContentPane().add(p_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 150, 80));

        member_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        member_ID.setText("MEMBERSHIP ID");
        getContentPane().add(member_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 150, 50));

        mem_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mem_name.setText("MEMBER NAME");
        getContentPane().add(mem_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 150, 80));

        book_I.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        book_I.setText("BOOK ID");
        getContentPane().add(book_I, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 150, 50));

        tax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tax.setText("FINE");
        getContentPane().add(tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 150, 80));

        MID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDActionPerformed(evt);
            }
        });
        MID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MIDKeyReleased(evt);
            }
        });
        getContentPane().add(MID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 320, 40));

        member_name.setEditable(false);
        getContentPane().add(member_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 320, 40));

        book_ID.setEditable(false);
        getContentPane().add(book_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 320, 40));

        pay_ID.setEditable(false);
        getContentPane().add(pay_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 320, 40));

        fine.setEditable(false);
        getContentPane().add(fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 320, 40));

        done.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        done.setForeground(new java.awt.Color(0, 0, 102));
        done.setText("DONE");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        pay_details();
        
        
        close_window();
    }//GEN-LAST:event_doneActionPerformed

    private void MIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_MIDActionPerformed

    private void MIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MIDKeyReleased
        // TODO add your handling code here:
        get_details(MID.getText());
        get_ID();
        get_data(MID.getText());
    }//GEN-LAST:event_MIDKeyReleased

    public void close_window()
    {
        WindowEvent new_event;
        
        new_event = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new_event);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_MEMBERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_MEMBERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_MEMBERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_REMOVE_MEMBERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAYMENT_WINDOW().setVisible(true);
            }
        });
    }
    
     
    
    public void get_data(String id)
    {
        Integer mid = Integer.valueOf(id);
        
        String SQL = "SELECT * FROM return_table WHERE Membership_ID = "+id+"";
        
         java.sql.Connection connection = Connector.connection();
         
         try
         {
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
            
                MID.setText(rs.getString("MEMBERSHIP_ID"));
                
                book_ID.setText(rs.getString("BOOK_NAME"));
                
                fine.setText(rs.getString("FINE"));
        
                
                member_name.setText(rs.getString("MEMBER_NAME"));
                      
            }
            
           
         }
         catch(Exception ERROR)
         {
             System.out.println(ERROR);
         }
    
    }
    
    public void get_ID()
    {
        Random rand = new Random();
        
        int maxNumber = 100000;
        
        int randomNumber = rand.nextInt(maxNumber) + 1;

        String PID = String.valueOf(randomNumber);
        
        pay_ID.setText(PID);
        
        
    }
    
     public void get_details(String id)
    {
        Integer mid = Integer.valueOf(id);
        
        String SQL = "SELECT * FROM members WHERE Membership_ID = "+id+"";
        
         java.sql.Connection connection = Connector.connection();
         
         try
         {
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
            
                
                member_name.setText(rs.getString("MEMBER_NAME"));
                      
            }
            
           
         }
         catch(Exception ERROR)
         {
             System.out.println(ERROR);
         }
    
    }
     
    public void pay_details()
    {
      
        
        Random rand = new Random();
        
        int maxNumber = 100000;
        
        int randomNumber = rand.nextInt(maxNumber) + 1;

        String PID = String.valueOf(randomNumber);
                
        String FINE = fine.getText();
        
        String membership_ID = MID.getText();
        
        
        
        java.sql.Connection connection = Connector.connection();
        
        String SQL = "INSERT INTO payments VALUES ('"+PID+"','"+FINE+"','"+membership_ID+"') ";
        
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           System.out.println("PAYMENT DONE Successfully !!");
           
           String message = "You Just Done Your Payment by : LKR "+fine.getText()+"<br><br> Payment ID : "+pay_ID.getText()+".";
           
           get_mail_address.extract_emails(membership_ID, "PAYMENT NOTIFICATION", message);
           
           JOptionPane.showMessageDialog(null,"Payment done Successfully !!! You can lend another book !!!!");

        }
        catch(Exception error)
        {
            System.out.println("ERROR CODE : "+error);
            
            JOptionPane.showMessageDialog(null,"Attempt Unsuccessful");
        }
           
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MID;
    private javax.swing.JLabel book_I;
    private javax.swing.JTextField book_ID;
    private javax.swing.JButton done;
    private javax.swing.JTextField fine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mem_name;
    private javax.swing.JLabel member_ID;
    private javax.swing.JTextField member_name;
    private javax.swing.JLabel p_ID;
    private javax.swing.JTextField pay_ID;
    private javax.swing.JLabel tax;
    // End of variables declaration//GEN-END:variables
}
