import Dates.Getdate;
import SQL_Connector.Connector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Random;
import javax.swing.JOptionPane;

public class LEND_BOOKS extends javax.swing.JFrame {

    /**
     * Creates new form update_delete
     */
    public LEND_BOOKS() {
        initComponents();
        
        lending_panel.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LMI = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        CA = new javax.swing.JLabel();
        arrear = new javax.swing.JLabel();
        LD = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        cardA = new javax.swing.JTextField();
        arr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        member_ID = new javax.swing.JLabel();
        member_name = new javax.swing.JLabel();
        c_available = new javax.swing.JLabel();
        fine = new javax.swing.JLabel();
        ID_member = new javax.swing.JTextField();
        mem_name = new javax.swing.JTextField();
        available_card = new javax.swing.JTextField();
        tax = new javax.swing.JTextField();
        lending_panel = new javax.swing.JPanel();
        bd = new javax.swing.JTextField();
        lend_day = new javax.swing.JLabel();
        return_day = new javax.swing.JLabel();
        lend = new javax.swing.JTextField();
        return_date = new javax.swing.JTextField();
        BID = new javax.swing.JLabel();
        BOOK_NAME = new javax.swing.JLabel();
        b_name = new javax.swing.JTextField();
        l_date = new javax.swing.JButton();

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        LMI.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        LMI.setForeground(new java.awt.Color(0, 0, 153));
        LMI.setText("LIBRARY MEMBERSHIP ID");

        name.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(51, 0, 153));
        name.setText("NAME");

        CA.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        CA.setForeground(new java.awt.Color(51, 0, 153));
        CA.setText("CARD AVAILABILITY");

        arrear.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        arrear.setForeground(new java.awt.Color(0, 0, 153));
        arrear.setText("ARREARS");

        LD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LDKeyReleased(evt);
            }
        });

        n.setEditable(false);
        n.setBackground(new java.awt.Color(255, 255, 255));

        cardA.setEditable(false);
        cardA.setBackground(new java.awt.Color(255, 255, 255));
        cardA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardAActionPerformed(evt);
            }
        });

        arr.setEditable(false);
        arr.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LMI, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(LD, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(arrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(cardA, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(arr, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))))
                .addGap(202, 202, 202))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LMI))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CA)
                    .addComponent(cardA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrear))
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("LEND BOOKS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 140, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sltc.PNG"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 170));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 255));
        jLabel10.setText("LIBRARY MANAGEMENT SYSTEM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 400, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture_6.PNG"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 250, 280));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimalistic-wallpapers-collection-themefoxx (124).jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 590));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        member_ID.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        member_ID.setForeground(new java.awt.Color(0, 0, 153));
        member_ID.setText("MEMBERSHIP ID");

        member_name.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        member_name.setForeground(new java.awt.Color(51, 0, 153));
        member_name.setText("NAME");

        c_available.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        c_available.setForeground(new java.awt.Color(51, 0, 153));
        c_available.setText("CARD AVAILABILITY");

        fine.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        fine.setForeground(new java.awt.Color(0, 0, 153));
        fine.setText("FINES");

        ID_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_memberActionPerformed(evt);
            }
        });
        ID_member.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ID_memberKeyReleased(evt);
            }
        });

        mem_name.setEditable(false);
        mem_name.setBackground(new java.awt.Color(255, 255, 255));
        mem_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mem_nameActionPerformed(evt);
            }
        });

        available_card.setEditable(false);
        available_card.setBackground(new java.awt.Color(255, 255, 255));
        available_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                available_cardActionPerformed(evt);
            }
        });

        tax.setEditable(false);
        tax.setBackground(new java.awt.Color(255, 255, 255));
        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(member_name, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_available, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fine, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(available_card, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(mem_name)
                            .addComponent(tax)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(member_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ID_member)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(member_ID))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(member_name)
                    .addComponent(mem_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_available)
                    .addComponent(available_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fine))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 660, -1));

        lending_panel.setBorder(new javax.swing.border.MatteBorder(null));

        bd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bdKeyReleased(evt);
            }
        });

        lend_day.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        lend_day.setForeground(new java.awt.Color(0, 0, 153));
        lend_day.setText("LEND DATE");

        return_day.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        return_day.setForeground(new java.awt.Color(51, 0, 153));
        return_day.setText("RETURN DATE");

        lend.setEditable(false);
        lend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendActionPerformed(evt);
            }
        });

        return_date.setEditable(false);
        return_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_dateActionPerformed(evt);
            }
        });

        BID.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        BID.setForeground(new java.awt.Color(0, 0, 153));
        BID.setText("BOOK ID");

        BOOK_NAME.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        BOOK_NAME.setForeground(new java.awt.Color(0, 0, 153));
        BOOK_NAME.setText("BOOK NAME");

        b_name.setEditable(false);
        b_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b_nameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout lending_panelLayout = new javax.swing.GroupLayout(lending_panel);
        lending_panel.setLayout(lending_panelLayout);
        lending_panelLayout.setHorizontalGroup(
            lending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lending_panelLayout.createSequentialGroup()
                .addGroup(lending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BID, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOOK_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lend_day, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(return_day, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(lending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bd, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(lend)
                    .addComponent(b_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(return_date))
                .addGap(28, 28, 28))
        );
        lending_panelLayout.setVerticalGroup(
            lending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lending_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BID)
                    .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOOK_NAME)
                    .addComponent(b_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(lending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lending_panelLayout.createSequentialGroup()
                        .addComponent(lend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(return_date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lending_panelLayout.createSequentialGroup()
                        .addComponent(lend_day)
                        .addGap(18, 18, 18)
                        .addComponent(return_day)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(lending_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 660, 180));

        l_date.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        l_date.setText("DONE");
        l_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_dateActionPerformed(evt);
            }
        });
        getContentPane().add(l_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_LDKeyReleased

    private void cardAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardAActionPerformed

    private void ID_memberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ID_memberKeyReleased
       get_data(ID_member.getText());
        
    }//GEN-LAST:event_ID_memberKeyReleased

    private void available_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_available_cardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_available_cardActionPerformed

    private void lendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lendActionPerformed

    private void return_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_return_dateActionPerformed

    private void ID_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_memberActionPerformed

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxActionPerformed

    private void mem_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mem_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mem_nameActionPerformed

    private void bdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bdKeyReleased
        // TODO add your handling code here:
        get_dates();
        get_details(bd.getText());
        
    }//GEN-LAST:event_bdKeyReleased

    private void l_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_dateActionPerformed
        // TODO add your handling code here:
        Lend_Books();
    }//GEN-LAST:event_l_dateActionPerformed

    private void b_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_nameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_b_nameKeyReleased
    
    public void get_data(String id)
    {
        Integer mid = Integer.valueOf(id);
        
        get_status(id);
        
        lend_handler(id);
        
        String SQL = "SELECT * FROM members WHERE Membership_ID = "+id+"";
        
         java.sql.Connection connection = Connector.connection();
         
         try
         {
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
                mem_name.setText(rs.getString("MEMBER_NAME"));
            }
         }
                
         catch(Exception ERROR)
         {
             System.out.println(ERROR);
         }
    
    }
    
    public void get_dates()
    {
        String Date_  = Dates.Getdate.today();
        
        String RDate = Dates.Getdate.return_date(14);
        
        lend.setText(Date_);
        
        return_date.setText(RDate);
    }
    
    public void get_details(String id)
    {
        Integer bid = Integer.valueOf(id);
        
        String SQL = "SELECT * FROM books WHERE BOOK_ID = "+id+"";
        
        
        
         java.sql.Connection connection = Connector.connection();
         
         try
         {
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
            
            while(rs.next())
            {
                b_name.setText(rs.getString("BOOK_NAME"));
            }
         }
                
         catch(Exception ERROR)
         {
             System.out.println(ERROR);
         }
    
    }
    
    public void Lend_Books()
    {
        Random rand = new Random();
        
        int maxNumber = 100000;
        
        int randomNumber = rand.nextInt(maxNumber) + 1;

        String LID = String.valueOf(randomNumber);
                
        String Lend_Date = lend.getText();
        
        String Return_Date = return_date.getText();
        
        String membership_ID = ID_member.getText();
        
        String book_ID = bd.getText();
        
        String book_Name = b_name.getText();
        
        java.sql.Connection connection = Connector.connection();
        
        String SQL = "INSERT INTO lend_books VALUES ('"+LID+"','"+Lend_Date+"','"+Return_Date+"','"+membership_ID+"','"+book_ID+"','"+book_Name+"') ";
        
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           System.out.println("Data Insert Successfully !!");
           
           String message = "You Just Lent A Book : "+b_name.getText()+"<br><br> You Must Return this BOOK on : "+return_date.getText()+".";
           
           get_mail_address.extract_emails(membership_ID, "BOOK LENDING NOTIFICATION", message);
           
           JOptionPane.showMessageDialog(null,"Book Lended Successfully !!! You must return your book within 14 days !!!!");

        }
        catch(Exception error)
        {
            System.out.println("ERROR CODE : "+error);
            
            JOptionPane.showMessageDialog(null,"Attempt Unsuccessful");
        }
           
    }
    
    public void lend_handler(String card_ID)
    {
        Integer card_holder = Integer.valueOf(card_ID);
        
        int return_value = book_valid.validation_lending(card_holder);
        
        
        if(return_value == 0)
        {
            lending_panel.setVisible(true);
            available_card.setText("Card Available");  
        }
        else
        {
            lending_panel.setVisible(false);
            available_card.setText("Card Unavailable");  
        }
    }
    
     public void get_status(String id)
    {
        int validator = date_validator.get_return_date(id);
        
        if(validator == 0)
        {
           
             
            
        }
        if(validator > 0)
        {
           
            
            
            
        }
        else
        {
            int late_dates = Math.abs(validator);
            
            
            
            tax.setText(String.valueOf(late_dates*50));
            
            
        }
        
    }
   
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEND_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEND_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEND_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEND_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEND_BOOKS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BID;
    private javax.swing.JLabel BOOK_NAME;
    private javax.swing.JLabel CA;
    private javax.swing.JTextField ID_member;
    private javax.swing.JTextField LD;
    private javax.swing.JLabel LMI;
    private javax.swing.JTextField arr;
    private javax.swing.JLabel arrear;
    private javax.swing.JTextField available_card;
    private javax.swing.JTextField b_name;
    private javax.swing.JTextField bd;
    private javax.swing.JLabel c_available;
    private javax.swing.JTextField cardA;
    private javax.swing.JLabel fine;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton l_date;
    private javax.swing.JTextField lend;
    private javax.swing.JLabel lend_day;
    private javax.swing.JPanel lending_panel;
    private javax.swing.JTextField mem_name;
    private javax.swing.JLabel member_ID;
    private javax.swing.JLabel member_name;
    private javax.swing.JTextField n;
    private javax.swing.JLabel name;
    private javax.swing.JTextField return_date;
    private javax.swing.JLabel return_day;
    private javax.swing.JTextField tax;
    // End of variables declaration//GEN-END:variables
}
